/* 
Strings 1 + 2 and the comment should return no errors

The 3rd 'string' is not a character and should return an invalid token

The 4th string goes mulitple lines, return error

The 5th should return the same

The 6th should end off with an unterminated string error 
*/

"If these following strings contains errors, I will be very \n happy"

"When I \t wonder why \t what's never been's \t never been so"

'a veritable something'

"lalalalalalalalalalsssssssssssssssssssssssssssssssssssssssssssssssssssssssss
aghjkjhghjklkjhghjklkjhghjkljhghjklkjhghjkl"

/* I'm not a string but
I'm still valid! */

"It is intentional by the way,

"Something profound idk"